package com.example.signtranslator

import android.content.Context
import ai.runanywhere.sdk.RunAnywhere
import ai.runanywhere.sdk.model.LLMConfig
import ai.runanywhere.sdk.model.InferenceResult
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.withContext

/**
 * Helper class to manage on-device LLM inference using RunAnywhere SDK.
 * All processing is done locally and offline.
 */
class RunAnywhereHelper(private val context: Context) {

    private var runAnywhere: RunAnywhere? = null
    private val modelId = "isl-translator-model"

    /**
     * Initializes the RunAnywhere SDK and registers the LLM model from assets.
     * This ensures the model is loaded only once and is ready for offline use.
     */
    suspend fun initialize() = withContext(Dispatchers.IO) {
        if (runAnywhere != null) return@withContext

        // Step 1: Initialize the SDK context
        runAnywhere = RunAnywhere.init(context)

        // Step 2: Configure the LLM for on-device, offline-only use
        val config = LLMConfig.Builder()
            .setModelAssetPath("models/isl_language_model.bin") // Path in app/src/main/assets/
            .setContextWindow(1024)
            .setTemperature(0.5f)
            .setOfflineOnly(true) // Enforce no cloud calls
            .build()

        // Step 3: Register and load the model into memory
        runAnywhere?.registerModel(modelId, config)
    }

    /**
     * Performs a standard one-shot inference to translate gestures into text.
     */
    suspend fun translateGestures(gestures: String): String = withContext(Dispatchers.IO) {
        ensureInitialized()
        val prompt = "Rewrite these letters into a proper sentence: $gestures"
        
        val result = runAnywhere?.generate(modelId, prompt)
        return@withContext if (result is InferenceResult.Success) {
            result.text
        } else {
            "Translation error"
        }
    }

    /**
     * Returns a Flow that emits tokens in real-time as they are generated by the model.
     */
    fun streamTranslation(gestures: String): Flow<String> = flow {
        ensureInitialized()
        val prompt = "Rewrite these letters into a proper sentence: $gestures"
        
        runAnywhere?.streamGenerate(modelId, prompt)?.collect { token ->
            emit(token)
        }
    }

    private fun ensureInitialized() {
        if (runAnywhere == null) {
            throw IllegalStateException("RunAnywhere SDK not initialized. Call initialize() first.")
        }
    }

    /**
     * Clean up resources when done.
     */
    fun close() {
        runAnywhere?.close()
        runAnywhere = null
    }
}
